version: "3.9"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/pg-data:/var/lib/postgresql/data/

volumes:
  db-data: